### PR TITLE
increase font size for nav items

### PR DESCRIPTION
**Pull request by bifodus**

### CODE REVIEW

**Comment by bifodus** [comment]
this looks good until the nav items overlap the middle part of the header.  still trying to figure out how to avoid that without doing something funky like reorganizing the nav items.

the ipad mockup that the designer gave us just has really tiny font, unfortunately.  it looks good, but then you realize that it's only 768px horizontally, which puts the fonts down into the 8-12px range.  trying to come up with a workaround

**Comment by jsdevel** [comment]
maybe we collapse sooner?

**Comment by bifodus** [comment]
it starts to overlap at about 900 pixel width, which seems pretty high.
I'll play with it more today

**Comment by jsdevel** [comment]
:+1:

**Pull request merged**
